---
# main.yml tasks file for nutanix_prism_role_karbon_enable
- import_tasks: enable_karbon.yml
  when:
    - session_cookie is defined
    - prism_type == "pc"
    - not karbon_enabled
- import_tasks: download_images.yml
  when:
    - session_cookie is defined
    - prism_type == "pc"
    - karbon_enabled